namespace WinCal;

/// <summary>Minimal localization: Korean (default) / English string tables.</summary>
internal static class Loc
{
    public static bool Korean => App.Settings.Language != "en";

    public static string T(string key) =>
        (Korean ? Ko : En).TryGetValue(key, out var v) ? v : key;

    public static string F(string key, params object[] args) => string.Format(T(key), args);

    public static string[] Weekdays => Korean
        ? new[] { "일", "월", "화", "수", "목", "금", "토" }
        : new[] { "Su", "Mo", "Tu", "We", "Th", "Fr", "Sa" };

    private static readonly Dictionary<string, string> Ko = new()
    {
        ["tray_tip"] = "WinCal — 바탕화면 캘린더",
        ["btn_today"] = "오늘",
        ["btn_refresh"] = "새로고침",
        ["btn_gcal"] = "Google 캘린더",
        ["btn_settings"] = "설정",
        ["syncing"] = "동기화 중…",
        ["synced_fmt"] = "{0:HH:mm} 동기화됨",
        ["sync_failed_fmt"] = "⚠ 동기화 실패: {0}",
        ["sync_failed"] = "동기화 실패",
        ["month_fmt"] = "yyyy년 M월",
        ["more_fmt"] = "+{0} 더보기",
        ["no_title"] = "(제목 없음)",
        ["memo_title"] = "메모",
        ["memo_hint"] = "더블클릭하여 메모 작성",
        ["edit_hint"] = "드래그로 이동 · 우하단 파란 그립으로 크기 조절",
        ["done_lock"] = "완료 (잠금)",
        ["tray_refresh"] = "지금 새로고침",
        ["tray_gcal"] = "Google 캘린더 열기",
        ["tray_sticker"] = "스티커 추가",
        ["tray_position"] = "위치 조정",
        ["tray_lock"] = "위치 잠금",
        ["tray_settings"] = "설정",
        ["tray_exit"] = "종료",
        ["set_title"] = "WinCal 설정",
        ["set_ics_label"] = "Google 캘린더 ICS 비밀 주소 (한 줄에 하나씩, 여러 개 가능)",
        ["set_ics_hint"] = "캘린더 설정 → '비밀 주소(iCal 형식)'. 공휴일 등 구독 캘린더는 '공개 주소(iCal 형식)'를 추가로 넣으면 함께 표시됩니다. 캘린더별로 다른 색 점으로 구분됩니다.",
        ["set_font"] = "폰트",
        ["set_theme"] = "테마",
        ["set_language"] = "언어",
        ["set_monitor"] = "표시 모니터",
        ["set_refresh"] = "새로고침 주기 (분)",
        ["set_weekstart"] = "주 시작 요일",
        ["sunday"] = "일요일",
        ["monday"] = "월요일",
        ["fullscreen"] = "화면 전체 사용",
        ["sidememo"] = "우측 메모 영역 표시",
        ["size"] = "크기",
        ["region_hint"] = "위치는 트레이 메뉴 → '위치 조정'으로 드래그해서 옮길 수 있습니다",
        ["scale"] = "크기 배율",
        ["cell_opacity"] = "셀 불투명도",
        ["win_opacity"] = "전체 불투명도",
        ["startup"] = "Windows 시작 시 자동 실행",
        ["defaults"] = "기본값 복원",
        ["defaults_tip"] = "모양 관련 설정을 기본값으로 되돌립니다 (캘린더 주소는 유지)",
        ["save"] = "저장",
        ["cancel"] = "취소",
        ["delete"] = "삭제",
        ["sticker_title"] = "스티커",
        ["sticker_memo"] = "스티커 메모",
        ["monitor_fmt"] = "{0}번 모니터 ({1}×{2})",
        ["primary_suffix"] = " — 주",
        ["all_monitors"] = "모든 모니터",
        ["no_ics"] = "ICS URL이 설정되지 않았습니다",
    };

    private static readonly Dictionary<string, string> En = new()
    {
        ["tray_tip"] = "WinCal — Desktop Calendar",
        ["btn_today"] = "Today",
        ["btn_refresh"] = "Refresh",
        ["btn_gcal"] = "Google Calendar",
        ["btn_settings"] = "Settings",
        ["syncing"] = "Syncing…",
        ["synced_fmt"] = "Synced {0:HH:mm}",
        ["sync_failed_fmt"] = "⚠ Sync failed: {0}",
        ["sync_failed"] = "Sync failed",
        ["month_fmt"] = "MMMM yyyy",
        ["more_fmt"] = "+{0} more",
        ["no_title"] = "(No title)",
        ["memo_title"] = "Memo",
        ["memo_hint"] = "Double-click to edit",
        ["edit_hint"] = "Drag to move · blue grip to resize",
        ["done_lock"] = "Done (lock)",
        ["tray_refresh"] = "Refresh now",
        ["tray_gcal"] = "Open Google Calendar",
        ["tray_sticker"] = "Add sticker",
        ["tray_position"] = "Adjust position",
        ["tray_lock"] = "Lock position",
        ["tray_settings"] = "Settings",
        ["tray_exit"] = "Exit",
        ["set_title"] = "WinCal Settings",
        ["set_ics_label"] = "Google Calendar secret iCal addresses (one per line)",
        ["set_ics_hint"] = "Calendar settings → 'Secret address in iCal format'. Subscribed calendars (e.g. holidays) can be added via 'Public address in iCal format'. Each calendar gets a different colored dot.",
        ["set_font"] = "Font",
        ["set_theme"] = "Theme",
        ["set_language"] = "Language",
        ["set_monitor"] = "Monitor",
        ["set_refresh"] = "Refresh interval (min)",
        ["set_weekstart"] = "Week starts on",
        ["sunday"] = "Sunday",
        ["monday"] = "Monday",
        ["fullscreen"] = "Use full screen",
        ["sidememo"] = "Show side memo panel",
        ["size"] = "Size",
        ["region_hint"] = "Move it via tray menu → 'Adjust position'",
        ["scale"] = "Scale",
        ["cell_opacity"] = "Cell opacity",
        ["win_opacity"] = "Window opacity",
        ["startup"] = "Run at Windows startup",
        ["defaults"] = "Reset to defaults",
        ["defaults_tip"] = "Reset appearance settings (calendar URLs are kept)",
        ["save"] = "Save",
        ["cancel"] = "Cancel",
        ["delete"] = "Delete",
        ["sticker_title"] = "Sticker",
        ["sticker_memo"] = "Sticker memo",
        ["monitor_fmt"] = "Monitor {0} ({1}×{2})",
        ["primary_suffix"] = " — primary",
        ["all_monitors"] = "All monitors",
        ["no_ics"] = "No ICS URL configured",
    };
}
